"""
Django settings for attend_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# There is no fallback secret key. A default here would silently become the
# production signing key for sessions, password-reset links and anything else
# keyed off it, and the value would be readable in a public repository. Missing
# configuration should stop the process, not be papered over.
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY is not set. Define it in the environment (App Service "
        "application settings) or in backend/.env for local work."
    )

# Defaults to off. A deployment that forgets to set this gets the safe value,
# not a debug page with a traceback and settings dump on a public host.
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"

# The wildcard is gone: with "*" in the list, Host-header checking is disabled
# entirely, which is what makes cache-poisoning and password-reset-link
# poisoning possible. Deployments name their own hostname.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0,.up.railway.app,.railway.app,backend-production-b537.up.railway.app").split(",")
    if host.strip()
]
AUTH_USER_MODEL = 'attendance.User'

ACCOUNT_AUTHENTICATION_METHOD = 'email'  # Use email for login
ACCOUNT_EMAIL_REQUIRED = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'attendance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'attend_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'attend_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.getenv('WEBSITE_SITE_NAME'):
    db_path = '/home/db.sqlite3'
else:
    db_path = BASE_DIR / 'db.sqlite3'

DATABASES = {
    'default': dj_database_url.parse(
        os.getenv("DATABASE_URL", f"sqlite:///{db_path}")
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # Keep for admin
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from corsheaders.defaults import default_headers

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000,http://localhost:8080,http://localhost:5000,http://localhost:59371,https://backend-production-b537.up.railway.app,https://presence-cne6ezafcncnduf3.indiasouthcentral-01.azurewebsites.net",
    ).split(",")
    if origin.strip()
]

# Defaults to off. CORS_ALLOW_ALL_ORIGINS together with CORS_ALLOW_CREDENTIALS
# below is the combination that lets any origin make credentialed requests.
# Django serves the Flutter web build itself (see serve_flutter in urls.py), so
# the first-party client is same-origin and needs none of this.
CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "False").lower() == "true"
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000,https://backend-production-b537.up.railway.app,https://*.up.railway.app,https://*.railway.app,https://presence-cne6ezafcncnduf3.indiasouthcentral-01.azurewebsites.net",
    ).split(",")
    if origin.strip()
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    'bypass-tunnel-reminder',
    'content-type',
    'authorization',
]

CORS_ALLOW_CREDENTIALS = True

# --- Android App Links -----------------------------------------------------
#
# Served by attendance.views.assetlinks_json at
# /.well-known/assetlinks.json. Both values were previously hardcoded in that
# view, and the fingerprint there matched no key that this project can build:
# release signing used the machine-local debug keystore, whose fingerprint
# differs per machine. Configuration belongs in configuration, and an empty
# fingerprint list is an honest "not configured yet" rather than a claim about a
# key nobody holds.
#
# ANDROID_CERT_FINGERPRINTS is a comma-separated list of uppercase, colon-
# separated SHA-256 fingerprints of the *signing* certificates. With Play App
# Signing that is the fingerprint Play reports, not the one from your local
# upload keystore.
ANDROID_APP_PACKAGE = os.getenv("ANDROID_APP_PACKAGE", "com.campusguard.attendance")
ANDROID_CERT_FINGERPRINTS = [
    fp.strip()
    for fp in os.getenv("ANDROID_CERT_FINGERPRINTS", "").split(",")
    if fp.strip()
]
