# Generated by Django 5.0.7 on 2026-08-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_attendancesession_shape_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("enrolled", "Enrolled")],
                default="enrolled",
                max_length=20,
            ),
        ),
    ]
