# Generated by Django 5.0.7 on 2026-08-15 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_student_name_studentprofile_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='attendance.attendancerecord')),
            ],
            options={
                'db_table': 'attendance_audit_events',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='RegisteredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id_hash', models.CharField(max_length=64)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registered_devices',
            },
        ),
        migrations.CreateModel(
            name='AttendanceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unavailable', 'Unavailable'), ('timeout', 'Timeout'), ('invalid', 'Invalid')], max_length=20)),
                ('qr_freshness_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unavailable', 'Unavailable'), ('timeout', 'Timeout'), ('invalid', 'Invalid')], max_length=20)),
                ('session_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unavailable', 'Unavailable'), ('timeout', 'Timeout'), ('invalid', 'Invalid')], max_length=20)),
                ('student_eligibility_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unavailable', 'Unavailable'), ('timeout', 'Timeout'), ('invalid', 'Invalid')], max_length=20)),
                ('device_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unavailable', 'Unavailable'), ('timeout', 'Timeout'), ('invalid', 'Invalid')], max_length=20)),
                ('captcha_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unavailable', 'Unavailable'), ('timeout', 'Timeout'), ('invalid', 'Invalid')], max_length=20)),
                ('gyroscope_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unavailable', 'Unavailable'), ('timeout', 'Timeout'), ('invalid', 'Invalid')], max_length=20)),
                ('accelerometer_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unavailable', 'Unavailable'), ('timeout', 'Timeout'), ('invalid', 'Invalid')], max_length=20)),
                ('final_status', models.CharField(choices=[('teacher_review_required', 'Teacher Review Required'), ('verified', 'Verified'), ('teacher_cross_verified', 'Teacher Cross Verified'), ('teacher_rejected', 'Teacher Rejected')], max_length=40)),
                ('teacher_decision_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='attendance.attendancerecord')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_reviews', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.registereddevice')),
            ],
            options={
                'db_table': 'attendance_verifications',
            },
        ),
        migrations.AddConstraint(
            model_name='registereddevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_id_hash'), name='unique_user_device'),
        ),
    ]
