# Generated by Django 5.0.7 on 2026-08-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendanceauditevent_registereddevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='verification_reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='verification_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='board_type',
            field=models.CharField(blank=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='class_type',
            field=models.CharField(blank=True, default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='instruction_card',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='pattern_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='reference_images/'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='shape_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('flagged', 'Flagged')], default='present', max_length=20),
        ),
    ]
