# Generated by Django 5.0.7 on 2026-09-05 18:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_academicterm_attendanceflag_interventionlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('position_x_m', models.FloatField(blank=True, null=True)),
                ('position_y_m', models.FloatField(blank=True, null=True)),
                ('height_m', models.FloatField(blank=True, null=True)),
                ('ephemeral_key', models.BinaryField(max_length=32)),
                ('rotation_seconds', models.PositiveIntegerField(default=900)),
                ('battery_pct', models.PositiveIntegerField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'presence_anchors',
                'ordering': ['room', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('building', models.CharField(blank=True, max_length=120)),
                ('floor', models.CharField(blank=True, max_length=16)),
                ('length_meters', models.FloatField(blank=True, null=True)),
                ('width_meters', models.FloatField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'presence_rooms',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RoomProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_version', models.CharField(max_length=64)),
                ('anchor_map', models.JSONField(blank=True, default=dict)),
                ('position_stats', models.JSONField(blank=True, default=dict)),
                ('expected_variance_db', models.FloatField(blank=True, null=True)),
                ('tolerance_db', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('survey_positions', models.PositiveIntegerField(default=0)),
                ('negative_positions', models.PositiveIntegerField(default=0)),
                ('calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'presence_room_profiles',
                'ordering': ['room', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionEpoch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.PositiveIntegerField()),
                ('first_step', models.PositiveIntegerField()),
                ('last_step', models.PositiveIntegerField()),
                ('issued_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'presence_session_epochs',
                'ordering': ['presence_session', 'epoch'],
            },
        ),
        migrations.CreateModel(
            name='StepHighWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[0-9a-f]{32}$', 'expected 32 lowercase hex characters (16 bytes)')])),
                ('device_key_id', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9a-f]{16}$', 'expected 16 lowercase hex characters (8 bytes)')])),
                ('step', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'presence_step_high_water',
            },
        ),
        migrations.AlterField(
            model_name='attendanceflag',
            name='flag_type',
            field=models.CharField(choices=[('low_verification', 'Low Verification Score'), ('burst_marking', 'Burst Marking (possible proxy cluster)'), ('session_collision', 'Session Collision (two places at once)'), ('late_outlier', 'Latency Outlier'), ('post_session_mark', 'Marked After Session End'), ('cohort_drop', 'Cohort Attendance Drop'), ('presence_secondary', 'Presence: Secondary Verification Needed'), ('presence_suspicious', 'Presence: Suspicious Evidence'), ('presence_refused', 'Presence: Proof Refused'), ('presence_not_verified', 'Presence: Not Verified')], max_length=32),
        ),
        migrations.CreateModel(
            name='AttendanceProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'expected 64 lowercase hex characters (32 bytes)')])),
                ('nonce', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[0-9a-f]{32}$', 'expected 32 lowercase hex characters (16 bytes)')])),
                ('step', models.PositiveIntegerField()),
                ('proof_bytes', models.BinaryField()),
                ('biometric', models.SmallIntegerField(choices=[(0, 'Not attempted (unsupported or not required)'), (1, 'Success'), (2, 'Failed'), (3, 'Cancelled by student')], default=0)),
                ('platform', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Android'), (2, 'iOS'), (3, 'Web')], default=0)),
                ('capabilities', models.PositiveIntegerField(default=0)),
                ('captured_at_claim', models.BigIntegerField()),
                ('claimed_status', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Present'), (2, 'Secondary verification'), (3, 'Not verified'), (4, 'Suspicious')], default=0)),
                ('claimed_confidence_milli', models.PositiveIntegerField(blank=True, null=True)),
                ('claimed_hop_count', models.PositiveIntegerField(blank=True, null=True)),
                ('received_at', models.BigIntegerField()),
                ('queued_seconds', models.IntegerField(blank=True, null=True)),
                ('validation_state', models.CharField(choices=[('received', 'Received, not yet judged'), ('accepted', 'Re-derived and judged'), ('refused', 'Refused before scoring'), ('duplicate', 'Already submitted (idempotent retry)')], default='received', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proof', to='attendance.attendancerecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'presence_proofs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64, unique=True)),
                ('artifact', models.JSONField(default=dict)),
                ('digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'expected 64 lowercase hex characters (32 bytes)')])),
                ('calibration', models.CharField(choices=[('field-validated', 'Field-validated'), ('simulator-fitted', 'Simulator-fitted'), ('uncalibrated', 'Uncalibrated')], max_length=32)),
                ('activation_checks', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_configs_activated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'presence_config_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresenceDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Present'), (2, 'Secondary verification'), (3, 'Not verified'), (4, 'Suspicious')])),
                ('millinats', models.IntegerField()),
                ('confidence_milli', models.PositiveIntegerField(blank=True, null=True)),
                ('ordering_only', models.BooleanField(default=True)),
                ('ordering_reason', models.CharField(blank=True, max_length=120)),
                ('coverage_pct', models.FloatField(blank=True, null=True)),
                ('supplied_pct', models.FloatField(blank=True, null=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('evidence_present', models.JSONField(blank=True, default=list)),
                ('evidence_missing', models.JSONField(blank=True, default=dict)),
                ('refused', models.BooleanField(default=False)),
                ('gate_code', models.CharField(blank=True, max_length=64)),
                ('calibration', models.CharField(choices=[('field-validated', 'Field-validated'), ('simulator-fitted', 'Simulator-fitted'), ('uncalibrated', 'Uncalibrated')], max_length=32)),
                ('config_version', models.CharField(max_length=64)),
                ('codec_version', models.CharField(blank=True, max_length=32)),
                ('room_profile_version', models.CharField(blank=True, max_length=64)),
                ('audit', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('proof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='attendance.attendanceproof')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_decisions', to='attendance.attendancerecord')),
            ],
            options={
                'db_table': 'presence_decisions',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_status', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Present'), (2, 'Secondary verification'), (3, 'Not verified'), (4, 'Suspicious')])),
                ('new_status', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Present'), (2, 'Secondary verification'), (3, 'Not verified'), (4, 'Suspicious')])),
                ('reason', models.TextField()),
                ('original_decision', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presence_overrides_made', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_overrides', to='attendance.attendancerecord')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='attendance.presencedecision')),
            ],
            options={
                'db_table': 'presence_manual_overrides',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresenceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_version', models.CharField(max_length=32)),
                ('config_version', models.CharField(max_length=64)),
                ('root_secret', models.BinaryField(max_length=32)),
                ('signing_seed', models.BinaryField(max_length=32)),
                ('signing_key_id', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9a-f]{16}$', 'expected 16 lowercase hex characters (8 bytes)')])),
                ('chain_start_unix', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('observations_purged_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='attendance.attendancesession')),
            ],
            options={
                'db_table': 'presence_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attendanceproof',
            name='presence_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='attendance.presencesession'),
        ),
        migrations.CreateModel(
            name='RegisteredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{16}$', 'expected 16 lowercase hex characters (8 bytes)')])),
                ('public_key', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'expected 64 lowercase hex characters (32 bytes)')])),
                ('platform', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Android'), (2, 'iOS'), (3, 'Web')], default=0)),
                ('capabilities', models.PositiveIntegerField(default=0)),
                ('device_profile_version', models.CharField(blank=True, max_length=64)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_devices_revoked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'presence_registered_devices',
                'ordering': ['student', '-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='PresenceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('origin', 'Direct teacher origin sighting'), ('relay', 'Relayed sighting'), ('anchor', 'Anchor sighting'), ('ranging', 'Precision ranging measurement')], max_length=12)),
                ('step', models.PositiveIntegerField()),
                ('observed_at_claim', models.BigIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presence_observations', to=settings.AUTH_USER_MODEL)),
                ('presence_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='attendance.presencesession')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='attendance.registereddevice')),
            ],
            options={
                'db_table': 'presence_observations',
                'ordering': ['presence_session', 'step'],
            },
        ),
        migrations.AddField(
            model_name='attendanceproof',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofs', to='attendance.registereddevice'),
        ),
        migrations.CreateModel(
            name='RelayChainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hop_count', models.PositiveIntegerField(default=0)),
                ('chain_bytes', models.BinaryField()),
                ('verified', models.BooleanField(default=False)),
                ('refusal_code', models.CharField(blank=True, max_length=64)),
                ('hop_pseudonyms', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chain', to='attendance.attendanceproof')),
            ],
            options={
                'db_table': 'presence_relay_chains',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'expected 64 lowercase hex characters (32 bytes)')])),
                ('session_id', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[0-9a-f]{32}$', 'expected 32 lowercase hex characters (16 bytes)')])),
                ('device_key_id', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9a-f]{16}$', 'expected 16 lowercase hex characters (8 bytes)')])),
                ('nonce', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[0-9a-f]{32}$', 'expected 32 lowercase hex characters (16 bytes)')])),
                ('step', models.PositiveIntegerField()),
                ('received_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'presence_replay_entries',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['session_id', 'device_key_id', 'step'], name='replay_high_step_idx'), models.Index(fields=['received_at'], name='replay_received_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='replayentry',
            constraint=models.UniqueConstraint(fields=('device_key_id', 'nonce'), name='presence_device_nonce_once'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building', 'floor'], name='room_bldg_floor_idx'),
        ),
        migrations.AddField(
            model_name='presencesession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='attendance.room'),
        ),
        migrations.AddField(
            model_name='anchor',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='attendance.room'),
        ),
        migrations.AddField(
            model_name='roomprofile',
            name='calibrated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_calibrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomprofile',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='attendance.room'),
        ),
        migrations.AddField(
            model_name='presencesession',
            name='room_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='attendance.roomprofile'),
        ),
        migrations.AddField(
            model_name='sessionepoch',
            name='presence_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epochs', to='attendance.presencesession'),
        ),
        migrations.AddConstraint(
            model_name='stephighwater',
            constraint=models.UniqueConstraint(fields=('session_id', 'device_key_id'), name='presence_high_water_once_per_device_session'),
        ),
        migrations.AddConstraint(
            model_name='configversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='presence_one_active_config'),
        ),
        migrations.AddIndex(
            model_name='presencedecision',
            index=models.Index(fields=['status', 'decided_at'], name='dec_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='presencedecision',
            index=models.Index(fields=['refused', 'gate_code'], name='dec_refused_code_idx'),
        ),
        migrations.AddIndex(
            model_name='presencedecision',
            index=models.Index(fields=['config_version'], name='dec_config_idx'),
        ),
        migrations.AddIndex(
            model_name='manualoverride',
            index=models.Index(fields=['actor', 'created_at'], name='ovr_actor_time_idx'),
        ),
        migrations.AddIndex(
            model_name='manualoverride',
            index=models.Index(fields=['new_status'], name='ovr_new_status_idx'),
        ),
        migrations.AddIndex(
            model_name='registereddevice',
            index=models.Index(fields=['student', 'is_active'], name='dev_student_live_idx'),
        ),
        migrations.AddIndex(
            model_name='registereddevice',
            index=models.Index(fields=['platform', 'is_active'], name='dev_platform_live_idx'),
        ),
        migrations.AddConstraint(
            model_name='registereddevice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='presence_one_active_device_per_student'),
        ),
        migrations.AddIndex(
            model_name='presenceobservation',
            index=models.Index(fields=['presence_session', 'student'], name='obs_sess_student_idx'),
        ),
        migrations.AddIndex(
            model_name='presenceobservation',
            index=models.Index(fields=['kind', 'step'], name='obs_kind_step_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceproof',
            index=models.Index(fields=['presence_session', 'student'], name='proof_sess_student_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceproof',
            index=models.Index(fields=['validation_state'], name='proof_state_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceproof',
            index=models.Index(fields=['device', 'step'], name='proof_device_step_idx'),
        ),
        migrations.AddIndex(
            model_name='relaychainrecord',
            index=models.Index(fields=['verified', 'hop_count'], name='chain_ok_hops_idx'),
        ),
        migrations.AddIndex(
            model_name='anchor',
            index=models.Index(fields=['is_active', 'last_seen_at'], name='anchor_live_seen_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='anchor',
            unique_together={('room', 'label')},
        ),
        migrations.AddConstraint(
            model_name='roomprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('room',), name='presence_one_active_profile_per_room'),
        ),
        migrations.AlterUniqueTogether(
            name='roomprofile',
            unique_together={('room', 'calibration_version')},
        ),
        migrations.AddIndex(
            model_name='presencesession',
            index=models.Index(fields=['room', 'created_at'], name='psess_room_created_idx'),
        ),
        migrations.AddIndex(
            model_name='presencesession',
            index=models.Index(fields=['closed_at'], name='psess_closed_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionepoch',
            index=models.Index(fields=['expires_at'], name='epoch_expires_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionepoch',
            unique_together={('presence_session', 'epoch')},
        ),
    ]
