# Generated by Django 5.0.7 on 2026-09-05 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Drop the unique index on `presence_proofs.record_id`.

    A mark does not have exactly one proof. A student recorded for review who later
    submits a proof that clears outright has two proofs bearing on one mark, and so
    does an offline queue that drains twice with a fresh nonce each time - both
    ordinary actions that the unique index turned into an IntegrityError. Widening
    is safe in both directions here: no row loses a value, and nothing read the
    `record.proof` accessor this renames to `record.proofs`.
    """


    dependencies = [
        ('attendance', '0014_anchor_room_roomprofile_sessionepoch_stephighwater_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceproof',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofs', to='attendance.attendancerecord'),
        ),
    ]
