# Generated by Django 5.0.7 on 2026-09-05 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Make `presence_proofs.digest` unique among accepted proofs only.

    A refused submission deliberately burns no nonce, so that the genuine copy of a
    proof somebody replayed with a bad signature still works. A plain unique index
    on `digest` cancelled that one layer up: the refused row made every later
    attempt at the same body collide, so one corrupted signature would answer the
    student's own retry with the refusal permanently. Attempts become rows, and the
    constraint keeps asserting what matters - one body is marked present at most
    once - which the replay ledger also asserts from the other side.
    """


    dependencies = [
        ('attendance', '0015_proof_record_many_to_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceproof',
            name='digest',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'expected 64 lowercase hex characters (32 bytes)')]),
        ),
        migrations.AddIndex(
            model_name='attendanceproof',
            index=models.Index(fields=['digest'], name='proof_digest_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendanceproof',
            constraint=models.UniqueConstraint(condition=models.Q(('validation_state', 'accepted')), fields=('digest',), name='presence_proof_digest_accepted_once'),
        ),
    ]
